module.exports = {
  client: {
    GAME_CREATE: 'GAME_CREATE',
    GAME_JOIN: 'GAME_JOIN',
    GAME_LEAVE: 'GAME_LEAVE',
    GAME_CHAT_MESSAGE: 'GAME_CHAT_MESSAGE',
    GAME_START: 'GAME_START',
    GAMES_UPDATE_REQUEST: 'GAMES_UPDATE_REQUEST',
    GAME_PIECE_MOVE: 'GAME_PIECE_MOVE',
    GAME_PIECE_ROTATE: 'GAME_PIECE_ROTATE',
  },
  server: {
    USER_CONNECTED: 'PLAYER_CONNECTED',
    ROOMS_UPDATE: 'ROOMS_UPDATE',
    GAME_CHAT_MESSAGE: 'GAME_CHAT_MESSAGE',
    ROOM_INFO_UPDATE: 'ROOM_INFO_UPDATE',
    GAME_STARTED: 'GAME_STARTED',
    GAME_PIECE_CURRENT: 'GAME_PIECE_CURRENT',
    GAME_BOARD_CURRENT: 'GAME_BOARD_CURRENT'
  }
};
