module.exports = {
  client: {
    GAME_CREATE: "GAME_CREATE",
    GAME_JOIN: "GAME_JOIN",
    GAME_LEAVE: "GAME_LEAVE",
    GAME_CHAT_MESSAGE: "GAME_CHAT_MESSAGE",
    GAME_START: "GAME_START",
    GAME_PIECE_MOVE: "GAME_PIECE_MOVE"
  },
  server: {
    USER_CONNECTED: 'PLAYER_CONNECTED',
    GAMES_UPDATE: 'GAMES_UPDATE',
    GAMES_UPDATE_REQUEST: 'GAMES_UPDATE_REQUEST',
    GAME_CHAT_MESSAGE: 'GAME_CHAT_MESSAGE',
    GAME_INFO_UPDATE: 'GAME_INFO_UPDATE',
    GAME_STARTED: 'GAME_STARTED',
    GAME_PIECE_CURRENT: 'GAME_PIECE_CURRENT',
    GAME_BOARD_CURRENT: 'GAME_BOARD_CURRENT'
  }
};
