"use strict";

module.exports = {
  client: {
    GAME_CREATE: "GAME_CREATE",
    GAME_JOIN: "GAME_JOIN",
    GAME_LEAVE: "GAME_LEAVE",
    GAME_CHAT_MESSAGE: "GAME_CHAT_MESSAGE",
  },
  server: {
    PLAYER_CONNECTED: "PLAYER_CONNECTED",
    GAMES_UPDATE: "GAMES_UPDATE",
    GAMES_UPDATE_REQUEST: "GAMES_UPDATE_REQUEST",
    GAME_CHAT_MESSAGE: "GAME_CHAT_MESSAGE",
  }
};
